name: fileuploadhistory

services:
  azure-db:
    image: mcr.microsoft.com/azure-sql-edge
    user: root
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Test12345!"
    ports:
      - "1433:1433"
    healthcheck:
      test: exit 0
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 20s
      start_interval: 30s

  init-script:
    build:
      context: .
      dockerfile: init.Dockerfile
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Test12345!"
      DB_HOST: azure-db
      DB_PORT: 1433
    depends_on:
      azure-db:
        condition: service_healthy
